# 接口名称: 获取分类下热门成交数据
# 来源文档: spider_process.md
# 说明: 根据 `topCode` 拉取某个行情分类下的成交排行。

@baseUrl = https://api.x-metash.cn

### 获取分类下热门成交数据
POST {{baseUrl}}/h5/market/topArchivePage
Content-Type: application/json

{
  "timeType": 0,
  "pageNum": 1,
  "pageSize": 50,
  "topCode": "759475"
}

### 带完整筛选字段的请求样本
POST {{baseUrl}}/h5/market/topArchivePage
Content-Type: application/json

{
  "timeType": 0,
  "pageNum": 1,
  "pageSize": 50,
  "dealCountSortType": false,
  "platformIdList": [],
  "communityIpIdList": [],
  "isAllPlatform": null,
  "isAllCommunityIp": null,
  "minPrice": null,
  "maxPrice": null,
  "beginTime": null,
  "endTime": null,
  "searchName": "",
  "planeCode": null,
  "topCode": "759475"
}

### 完整响应样本
# 见: 10_market_top_archive_page.response.json


### 原始响应样本: 10_market_top_archive_page.response.json
# {
#   "code" : 200,
#   "msg" : "成功",
#   "data" : {
#     "records" : [ {
#       "archiveId" : 30056,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/07/11/IMG_1319_20240711204651A788.jpeg",
#       "archiveName" : "小金猫",
#       "sellingCount" : 10365,
#       "dealCount" : 236,
#       "marketAmount" : 47025000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 28.50,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 28.57,
#       "avgAmountRate" : -0.59,
#       "upRate" : 0.63,
#       "dealAmount" : 6742.49,
#       "dealAmountRate" : -78.92,
#       "publishCount" : 1650000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -835,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 42679,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/08/29/mmexport1756468883535_20250829200243A085.jpg",
#       "archiveName" : "“赓续文脉”印章雕塑",
#       "sellingCount" : 306,
#       "dealCount" : 9,
#       "marketAmount" : 2396000.00,
#       "marketAmountRate" : -0.83,
#       "minAmount" : 299.50,
#       "minAmountRate" : -0.83,
#       "avgAmount" : 305.21,
#       "avgAmountRate" : -4.99,
#       "upRate" : 3.83,
#       "dealAmount" : 2746.90,
#       "dealAmountRate" : -73.28,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -196,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 48810,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/10/30/7f698ba6c9d74e3c887ef24b21f1f3f3_20251030104225A963.jpg",
#       "archiveName" : "张旭《古诗四帖》卷",
#       "sellingCount" : 251,
#       "dealCount" : 9,
#       "marketAmount" : 1888000.00,
#       "marketAmountRate" : 6.31,
#       "minAmount" : 236.00,
#       "minAmountRate" : 6.31,
#       "avgAmount" : 229.11,
#       "avgAmountRate" : 3.40,
#       "upRate" : 3.14,
#       "dealAmount" : 2062.00,
#       "dealAmountRate" : 32.95,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 162.22,
#       "distanceSellDay" : -132,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 48272,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/10/11/9c9f4f19a57b4dc1b5535c975d6366b2_20251011005003A781.png",
#       "archiveName" : "《共产党宣言》手稿",
#       "sellingCount" : 679,
#       "dealCount" : 6,
#       "marketAmount" : 7392000.00,
#       "marketAmountRate" : -0.32,
#       "minAmount" : 616.00,
#       "minAmountRate" : -0.32,
#       "avgAmount" : 616.00,
#       "avgAmountRate" : -1.46,
#       "upRate" : 5.66,
#       "dealAmount" : 3696.00,
#       "dealAmountRate" : -88.84,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -151,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 31990,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/10/11/微信图片_20241011210844_20241011210911A626.jpg",
#       "archiveName" : "清明上河图",
#       "sellingCount" : 381,
#       "dealCount" : 4,
#       "marketAmount" : 16500000.00,
#       "marketAmountRate" : -4.31,
#       "minAmount" : 2200.00,
#       "minAmountRate" : -4.31,
#       "avgAmount" : 2303.50,
#       "avgAmountRate" : 0.86,
#       "upRate" : 5.08,
#       "dealAmount" : 9214.00,
#       "dealAmountRate" : -32.76,
#       "publishCount" : 7500,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -513,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 29574,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/06/20/微信图片_20240620141654_20240620141713A973.jpg",
#       "archiveName" : "五牛图",
#       "sellingCount" : 248,
#       "dealCount" : 4,
#       "marketAmount" : 5500000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 550.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 542.50,
#       "avgAmountRate" : -0.82,
#       "upRate" : 2.48,
#       "dealAmount" : 2170.00,
#       "dealAmountRate" : -71.66,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -628,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 48720,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/10/24/d315dc369ec14bcabcbef0e6d2056e97_20251024212041A849.jpg",
#       "archiveName" : "良渚文化•神人兽面纹玉琮王",
#       "sellingCount" : 367,
#       "dealCount" : 3,
#       "marketAmount" : 2856000.00,
#       "marketAmountRate" : -2.06,
#       "minAmount" : 238.00,
#       "minAmountRate" : -2.06,
#       "avgAmount" : 243.00,
#       "avgAmountRate" : -2.39,
#       "upRate" : 3.06,
#       "dealAmount" : 729.00,
#       "dealAmountRate" : -85.36,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 164.44,
#       "distanceSellDay" : -137,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 37193,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/03/19/IMG_3188_20250319205046A473.jpeg",
#       "archiveName" : "《万里长城》",
#       "sellingCount" : 200,
#       "dealCount" : 2,
#       "marketAmount" : 4260000.00,
#       "marketAmountRate" : -1.39,
#       "minAmount" : 355.00,
#       "minAmountRate" : -1.39,
#       "avgAmount" : 364.50,
#       "avgAmountRate" : -1.35,
#       "upRate" : 1.67,
#       "dealAmount" : 729.00,
#       "dealAmountRate" : -1.35,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -353,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 41681,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/07/16/IMG_0996 2_20250716225354A554.jpg",
#       "archiveName" : "宋·赵佶《草书千字文》",
#       "sellingCount" : 175,
#       "dealCount" : 2,
#       "marketAmount" : 3320000.00,
#       "marketAmountRate" : 7.24,
#       "minAmount" : 415.00,
#       "minAmountRate" : 7.24,
#       "avgAmount" : 386.00,
#       "avgAmountRate" : 2.80,
#       "upRate" : 2.19,
#       "dealAmount" : 772.00,
#       "dealAmountRate" : -89.18,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 361.11,
#       "distanceSellDay" : -235,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 32481,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/10/31/微信图片_20241031211832_20241031211850A460.jpg",
#       "archiveName" : "百骏图",
#       "sellingCount" : 144,
#       "dealCount" : 2,
#       "marketAmount" : 4188000.00,
#       "marketAmountRate" : 1.65,
#       "minAmount" : 1047.00,
#       "minAmountRate" : 1.65,
#       "avgAmount" : 1044.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 3.60,
#       "dealAmount" : 2088.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 4000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -503,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 35340,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/05/25/企业微信截图_20250525123407_20250525123440A772.png",
#       "archiveName" : "商金杖",
#       "sellingCount" : 204,
#       "dealCount" : 2,
#       "marketAmount" : 2288000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 286.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 286.00,
#       "avgAmountRate" : 0.35,
#       "upRate" : 2.55,
#       "dealAmount" : 572.00,
#       "dealAmountRate" : 100.70,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -415,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14272,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161442A720.com/chain_myent/afts/img/4Fr7TrN6NCYAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : " 越王宝剑",
#       "sellingCount" : 278,
#       "dealCount" : 1,
#       "marketAmount" : 28150000.00,
#       "marketAmountRate" : -0.11,
#       "minAmount" : 2815.00,
#       "minAmountRate" : -0.11,
#       "avgAmount" : 6999.00,
#       "avgAmountRate" : 142.80,
#       "upRate" : 2.78,
#       "dealAmount" : 6999.00,
#       "dealAmountRate" : -19.07,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 27217,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/03/07/微信图片_20240307103819_20240307103859A097.jpg",
#       "archiveName" : "快雪时晴帖",
#       "sellingCount" : 57,
#       "dealCount" : 1,
#       "marketAmount" : 3278000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 1639.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 3000.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 2.85,
#       "dealAmount" : 3000.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 2000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -730,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14113,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161415A541.com/chain_myent/afts/img/NgRYS5gIYwgAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "元•青花萧何月下追韩信图梅瓶",
#       "sellingCount" : 181,
#       "dealCount" : 1,
#       "marketAmount" : 2392000.00,
#       "marketAmountRate" : -0.33,
#       "minAmount" : 299.00,
#       "minAmountRate" : -0.33,
#       "avgAmount" : 300.00,
#       "avgAmountRate" : 0.45,
#       "upRate" : 2.26,
#       "dealAmount" : 300.00,
#       "dealAmountRate" : -66.52,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 24571,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2023/11/10/蒙娜丽莎画框_20231110205708A916.png",
#       "archiveName" : "《蒙娜丽莎》-画框",
#       "sellingCount" : 150,
#       "dealCount" : 1,
#       "marketAmount" : 3460000.00,
#       "marketAmountRate" : 0.29,
#       "minAmount" : 346.00,
#       "minAmountRate" : 0.29,
#       "avgAmount" : 345.00,
#       "avgAmountRate" : -4.56,
#       "upRate" : 1.50,
#       "dealAmount" : 345.00,
#       "dealAmountRate" : -76.14,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -896,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 42762,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/09/03/企业微信截图_20250903193505_20250903193517A186.png",
#       "archiveName" : "赵佶《瑞鹤图》",
#       "sellingCount" : 292,
#       "dealCount" : 1,
#       "marketAmount" : 3444000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 287.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 320.00,
#       "avgAmountRate" : 11.65,
#       "upRate" : 2.43,
#       "dealAmount" : 320.00,
#       "dealAmountRate" : -87.59,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -184,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 31734,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/09/25/微信图片_20240925162633_20240925162651A998.jpg",
#       "archiveName" : "步辇图",
#       "sellingCount" : 377,
#       "dealCount" : 1,
#       "marketAmount" : 3750000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 375.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 376.00,
#       "avgAmountRate" : -0.03,
#       "upRate" : 3.77,
#       "dealAmount" : 376.00,
#       "dealAmountRate" : -80.01,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -534,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 31120,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/08/29/IMG_3948_20240829163201A658.jpeg",
#       "archiveName" : "《写生珍禽图》",
#       "sellingCount" : 186,
#       "dealCount" : 1,
#       "marketAmount" : 1590000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 159.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 159.00,
#       "avgAmountRate" : -10.24,
#       "upRate" : 1.86,
#       "dealAmount" : 159.00,
#       "dealAmountRate" : -88.78,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -562,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 28504,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/05/09/微信图片_20240509100936_20240509101336A661.jpg",
#       "archiveName" : "《冯摹兰亭序》",
#       "sellingCount" : 120,
#       "dealCount" : 1,
#       "marketAmount" : 3940000.00,
#       "marketAmountRate" : -0.18,
#       "minAmount" : 985.00,
#       "minAmountRate" : -0.18,
#       "avgAmount" : 1999.00,
#       "avgAmountRate" : 108.47,
#       "upRate" : 3.00,
#       "dealAmount" : 1999.00,
#       "dealAmountRate" : 108.47,
#       "publishCount" : 4000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -671,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 31973,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/10/09/微信图片_20241009174813_20241009174856A450.jpg",
#       "archiveName" : "辽·水月观音",
#       "sellingCount" : 118,
#       "dealCount" : 1,
#       "marketAmount" : 1510000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 151.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 151.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 1.18,
#       "dealAmount" : 151.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -521,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 13155,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161431A651.com/chain_myent/afts/img/2g4xTZ1x9NwAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "铜奔马",
#       "sellingCount" : 179,
#       "dealCount" : 1,
#       "marketAmount" : 18970000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 1897.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 2888.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 1.79,
#       "dealAmount" : 2888.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -976,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 25325,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2023/12/25/微信图片_20231225113425_20231225113448A364.jpg",
#       "archiveName" : "一号青铜神树",
#       "sellingCount" : 240,
#       "dealCount" : 1,
#       "marketAmount" : 3456000.00,
#       "marketAmountRate" : -0.69,
#       "minAmount" : 288.00,
#       "minAmountRate" : -0.69,
#       "avgAmount" : 305.00,
#       "avgAmountRate" : 5.17,
#       "upRate" : 2.00,
#       "dealAmount" : 305.00,
#       "dealAmountRate" : 5.17,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -810,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 39417,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/05/14/IMG_9647_20250514220147A192.jpg",
#       "archiveName" : "良渚文化·神人兽面纹玉钺王",
#       "sellingCount" : 245,
#       "dealCount" : 0,
#       "marketAmount" : 1408000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 176.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 3.06,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 60.00,
#       "overAmountRate" : 193.33,
#       "distanceSellDay" : -300,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 30610,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/08/03/IMG_2701_20240803130200A017.jpeg",
#       "archiveName" : "月王族PFP【合集】",
#       "sellingCount" : 418,
#       "dealCount" : 0,
#       "marketAmount" : 3575000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 715.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 8.36,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 5000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -583,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 49657,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/12/05/4c5c013dbe144b64a914d57c92f0a564_20251205210537A077.jpg",
#       "archiveName" : "辽青瓷飞鱼形水盂",
#       "sellingCount" : 157,
#       "dealCount" : 0,
#       "marketAmount" : 1600000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 200.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.96,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 122.22,
#       "distanceSellDay" : -95,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 49147,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/11/12/c38e9399ff3c40889ded30947e3e886b_20251112194132A842.jpg",
#       "archiveName" : "黄庭坚草书《诸上座帖》卷",
#       "sellingCount" : 174,
#       "dealCount" : 0,
#       "marketAmount" : 1568000.00,
#       "marketAmountRate" : -1.01,
#       "minAmount" : 196.00,
#       "minAmountRate" : -1.01,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 2.18,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 117.78,
#       "distanceSellDay" : -114,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 49559,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/12/03/cf04ca3b786444d78c7e24b2010fa91b_20251203204453A105.jpg",
#       "archiveName" : "青玉大禹治水图山子",
#       "sellingCount" : 200,
#       "dealCount" : 0,
#       "marketAmount" : 1160000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 116.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 2.00,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 28.89,
#       "distanceSellDay" : -97,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 30012,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/07/11/微信图片_20240711114759_20240711114848A041.jpg",
#       "archiveName" : "平复帖",
#       "sellingCount" : 71,
#       "dealCount" : 0,
#       "marketAmount" : 2316000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 1158.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 3.55,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 2000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -608,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 42785,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/09/04/企业微信截图_20250904103045_20250904103057A022.png",
#       "archiveName" : "陈仓石鼓·“吾车”石",
#       "sellingCount" : 57,
#       "dealCount" : 0,
#       "marketAmount" : 1345000.00,
#       "marketAmountRate" : -2.18,
#       "minAmount" : 269.00,
#       "minAmountRate" : -2.18,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.14,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 5000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -194,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 25235,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2023/12/20/微信图片_20231220153348_20231220153407A715.jpg",
#       "archiveName" : "金瓯永固杯",
#       "sellingCount" : 270,
#       "dealCount" : 0,
#       "marketAmount" : 2184000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 182.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 2.25,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -814,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 40392,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/10/20/8d00db6a97c94e3098e1723bd9910098_20251020185553A590.jpeg",
#       "archiveName" : "江山放牧图",
#       "sellingCount" : 215,
#       "dealCount" : 0,
#       "marketAmount" : 1610000.00,
#       "marketAmountRate" : -0.62,
#       "minAmount" : 161.00,
#       "minAmountRate" : -0.62,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 2.15,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 78.89,
#       "distanceSellDay" : -278,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14240,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161437A687.com/chain_myent/afts/img/dgTWTKgA7ucAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "晋侯鸟尊",
#       "sellingCount" : 157,
#       "dealCount" : 0,
#       "marketAmount" : 2690000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 269.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 1.57,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 36830,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/03/05/IMG_2715_20250305220959A706.jpeg",
#       "archiveName" : "田黄石乾隆帝三联印",
#       "sellingCount" : 121,
#       "dealCount" : 0,
#       "marketAmount" : 2328000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 388.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 2.02,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 6000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -366,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 27570,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/03/26/7b4dcbb107290843175a6bad5bf0fde_20240326135559A623.jpg",
#       "archiveName" : "祭侄文稿-3D",
#       "sellingCount" : 172,
#       "dealCount" : 0,
#       "marketAmount" : 4200000.00,
#       "marketAmountRate" : -0.47,
#       "minAmount" : 420.00,
#       "minAmountRate" : -0.47,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.72,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -720,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 41618,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/07/15/位图_20250715183640A010.png",
#       "archiveName" : "鲸探PFP体育世代1.0【合集】",
#       "sellingCount" : 203,
#       "dealCount" : 0,
#       "marketAmount" : 4450000.00,
#       "marketAmountRate" : -1.66,
#       "minAmount" : 890.00,
#       "minAmountRate" : -1.66,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 4.06,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 5000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -593,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14168,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161424A603.com/chain_myent/afts/img/GlAfR6caV80AAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "秦陵彩绘铜车马·一号车",
#       "sellingCount" : 168,
#       "dealCount" : 0,
#       "marketAmount" : 8460000.00,
#       "marketAmountRate" : -0.24,
#       "minAmount" : 846.00,
#       "minAmountRate" : -0.24,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.68,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 28763,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/05/23/微信图片_20240523094244_20240523094400A156.jpg",
#       "archiveName" : "曾侯乙编钟",
#       "sellingCount" : 74,
#       "dealCount" : 0,
#       "marketAmount" : 5850000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 975.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.23,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 6000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -661,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 24741,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2023/11/24/微信图片_20231124180528_20231124180546A023.jpg",
#       "archiveName" : "毛公鼎",
#       "sellingCount" : 170,
#       "dealCount" : 0,
#       "marketAmount" : 3990000.00,
#       "marketAmountRate" : -1.48,
#       "minAmount" : 399.00,
#       "minAmountRate" : -1.48,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.70,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -839,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14919,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122152419A309.com/chain_myent/afts/img/wj1eTYCTr8oAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "敦煌美术研究所幸运飞天",
#       "sellingCount" : 50,
#       "dealCount" : 0,
#       "marketAmount" : 26128000.00,
#       "marketAmountRate" : -0.67,
#       "minAmount" : 3266.00,
#       "minAmountRate" : -0.67,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 0.63,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 26343,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/02/18/微信图片_20240218103002_20240218103453A860.jpg",
#       "archiveName" : "青铜立人像",
#       "sellingCount" : 149,
#       "dealCount" : 0,
#       "marketAmount" : 3117600.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 259.80,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 1.24,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -755,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14920,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122152419A310.com/chain_myent/afts/img/V9JiQZ_FeCsAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "敦煌美术研究所祥瑞鹿王",
#       "sellingCount" : 53,
#       "dealCount" : 0,
#       "marketAmount" : 20000000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 2500.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 0.66,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 32052,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/10/11/微信图片_20241011203205_20241011203226A472.jpg",
#       "archiveName" : "《江山如此多娇》",
#       "sellingCount" : 109,
#       "dealCount" : 0,
#       "marketAmount" : 4640000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 580.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 1.36,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -515,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 25532,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2024/01/04/微信图片_20240104102353_20240104102730A373.jpg",
#       "archiveName" : "《溪山行旅图》",
#       "sellingCount" : 199,
#       "dealCount" : 0,
#       "marketAmount" : 2072000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 259.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 2.49,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 8000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -797,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 39633,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/05/21/mmexport1747832087376_20250521205603A305.jpg",
#       "archiveName" : "周昉《挥扇仕女图》卷",
#       "sellingCount" : 212,
#       "dealCount" : 0,
#       "marketAmount" : 3390000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 339.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 2.12,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 276.67,
#       "distanceSellDay" : -289,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14258,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161439A705.com/chain_myent/afts/img/uJxsRJ_piOMAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "长信宫灯",
#       "sellingCount" : 96,
#       "dealCount" : 0,
#       "marketAmount" : 4888000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 488.80,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 0.96,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 13257,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161429A638.com/chain_myent/afts/img/dTApQZguYkAAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "圆明园虎首铜像",
#       "sellingCount" : 259,
#       "dealCount" : 0,
#       "marketAmount" : 5380000.00,
#       "marketAmountRate" : -2.18,
#       "minAmount" : 269.00,
#       "minAmountRate" : -2.18,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 1.30,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 20000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -976,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 14226,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta_goods/2025/01/22/20250122161433A667.com/chain_myent/afts/img/\t-aIlToUeraUAAAAAAAAAAAAADvN2AQBr/480w_480h",
#       "archiveName" : "莲鹤方壶",
#       "sellingCount" : 128,
#       "dealCount" : 0,
#       "marketAmount" : 3580000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 358.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 1.28,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -937,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 41619,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/07/15/位图_20250715184155A017.png",
#       "archiveName" : "方尖龙PFP【合集】",
#       "sellingCount" : 211,
#       "dealCount" : 0,
#       "marketAmount" : 5440000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 1088.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 4.22,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 5000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -352,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 40694,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/06/18/mmexport1750251910014_20250618210542A699.jpg",
#       "archiveName" : "顾恺之《女史箴图》",
#       "sellingCount" : 361,
#       "dealCount" : 0,
#       "marketAmount" : 3660000.00,
#       "marketAmountRate" : -0.59,
#       "minAmount" : 305.00,
#       "minAmountRate" : -0.59,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.00,
#       "upRate" : 3.01,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : -100.00,
#       "publishCount" : 12000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 90.00,
#       "overAmountRate" : 238.89,
#       "distanceSellDay" : -262,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     }, {
#       "archiveId" : 35576,
#       "archiveImg" : "https://cdn2.x-metash.cn/XMeta/2025/01/23/微信图片_20250123231212_20250123231229A546.jpg",
#       "archiveName" : "展子虔《游春图》卷",
#       "sellingCount" : 242,
#       "dealCount" : 0,
#       "marketAmount" : 2640000.00,
#       "marketAmountRate" : 0.00,
#       "minAmount" : 264.00,
#       "minAmountRate" : 0.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : 0.00,
#       "upRate" : 2.42,
#       "dealAmount" : 0.00,
#       "dealAmountRate" : 0.00,
#       "publishCount" : 10000,
#       "platformId" : 741,
#       "dealCountRate" : null,
#       "isFollow" : null,
#       "salesAmount" : 0.00,
#       "overAmountRate" : 0.00,
#       "distanceSellDay" : -402,
#       "isTransfer" : true,
#       "costPerformance" : null,
#       "impactFraction" : null
#     } ],
#     "total" : 50,
#     "size" : 50,
#     "current" : 1,
#     "orders" : [ ],
#     "optimizeCountSql" : true,
#     "hitCount" : false,
#     "countId" : null,
#     "maxLimit" : null,
#     "searchCount" : true,
#     "pages" : 1
#   }
# }
# 

