# 接口名称: 获取 IP 方热榜成交量情况
# 来源文档: spider_process.md
# 说明: 查询 IP 维度的成交排行与市场指标。

@baseUrl = https://api.x-metash.cn

### 获取 IP 方热榜成交量情况
POST {{baseUrl}}/h5/market/ipPage
Content-Type: application/json
{"timeType":0,"pageNum":1,"pageSize":50,"platformIdList":[],"communityIpIdList":[],"isAllPlatform":null,"isAllCommunityIp":null,"minPrice":null,"maxPrice":null,"beginTime":null,"endTime":null,"searchName":"","planeCode":null}


### 完整响应样本
# 见: 11_market_ip_page.response.json


### 原始响应样本: 11_market_ip_page.response.json
# {
#   "code" : 200,
#   "msg" : "成功",
#   "data" : {
#     "records" : [ {
#       "archiveCount" : 186,
#       "communityIpId" : 29,
#       "marketAmount" : 132312049.16,
#       "marketAmountRate" : 0.0700,
#       "hot" : 0.89,
#       "hotRate" : -78.95,
#       "avgAmount" : 132.87,
#       "avgAmountRate" : -99.1800,
#       "dealCount" : 168,
#       "dealCountRate" : 21.0500,
#       "publishCount" : 844414,
#       "isFollow" : false,
#       "name" : "故宫宫苑",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415162341A375.png"
#     }, {
#       "archiveCount" : 185,
#       "communityIpId" : 32,
#       "marketAmount" : 97296137.28,
#       "marketAmountRate" : -0.5600,
#       "hot" : 0.04,
#       "hotRate" : -82.61,
#       "avgAmount" : 428.38,
#       "avgAmountRate" : -86.7400,
#       "dealCount" : 8,
#       "dealCountRate" : 17.3900,
#       "publishCount" : 852672,
#       "isFollow" : false,
#       "name" : "中国文促会",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415175342A923.png"
#     }, {
#       "archiveCount" : 109,
#       "communityIpId" : 30,
#       "marketAmount" : 77160983.77,
#       "marketAmountRate" : -0.7700,
#       "hot" : 1.95,
#       "hotRate" : -74.81,
#       "avgAmount" : 119.58,
#       "avgAmountRate" : -98.9300,
#       "dealCount" : 230,
#       "dealCountRate" : 25.1900,
#       "publishCount" : 600476,
#       "isFollow" : false,
#       "name" : "故宫观唐",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415163101A435.png"
#     }, {
#       "archiveCount" : 249,
#       "communityIpId" : 33,
#       "marketAmount" : 56474970.99,
#       "marketAmountRate" : 0.0900,
#       "hot" : 0.70,
#       "hotRate" : -64.30,
#       "avgAmount" : 68.33,
#       "avgAmountRate" : -98.1900,
#       "dealCount" : 176,
#       "dealCountRate" : 35.7000,
#       "publishCount" : 840808,
#       "isFollow" : false,
#       "name" : "雅昌艺术",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415180059A043.png"
#     }, {
#       "archiveCount" : 299,
#       "communityIpId" : 25,
#       "marketAmount" : 54986537.67,
#       "marketAmountRate" : 0.4100,
#       "hot" : 0.06,
#       "hotRate" : -92.14,
#       "avgAmount" : 84.45,
#       "avgAmountRate" : -98.6800,
#       "dealCount" : 18,
#       "dealCountRate" : 7.8600,
#       "publishCount" : 1014454,
#       "isFollow" : false,
#       "name" : "宽堂",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/03/24/位图_20250324215919A044.png"
#     }, {
#       "archiveCount" : 52,
#       "communityIpId" : 111,
#       "marketAmount" : 53687225.80,
#       "marketAmountRate" : 2.8500,
#       "hot" : 3.96,
#       "hotRate" : -68.01,
#       "avgAmount" : 233.55,
#       "avgAmountRate" : -98.0000,
#       "dealCount" : 222,
#       "dealCountRate" : 31.9900,
#       "publishCount" : 262438,
#       "isFollow" : false,
#       "name" : "辽宁省博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/16/default_20250816140853A757.jpg"
#     }, {
#       "archiveCount" : 460,
#       "communityIpId" : 34,
#       "marketAmount" : 48254261.46,
#       "marketAmountRate" : -0.0300,
#       "hot" : 0.06,
#       "hotRate" : -82.83,
#       "avgAmount" : 44.38,
#       "avgAmountRate" : -99.2600,
#       "dealCount" : 29,
#       "dealCountRate" : 17.1600,
#       "publishCount" : 473155,
#       "isFollow" : false,
#       "name" : "小熊网络",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415180633A109.png"
#     }, {
#       "archiveCount" : 44,
#       "communityIpId" : 117,
#       "marketAmount" : 38995047.00,
#       "marketAmountRate" : -0.9500,
#       "hot" : 13.80,
#       "hotRate" : -58.15,
#       "avgAmount" : 155.81,
#       "avgAmountRate" : -98.4200,
#       "dealCount" : 621,
#       "dealCountRate" : 41.8500,
#       "publishCount" : 227036,
#       "isFollow" : false,
#       "name" : "秦始皇帝陵博物院",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/19/WechatIMGe48d74237cf17ada1d8b2dacdb8ebe1f_20250819164433A079.jpeg"
#     }, {
#       "archiveCount" : 63,
#       "communityIpId" : 67,
#       "marketAmount" : 38292952.68,
#       "marketAmountRate" : -0.1500,
#       "hot" : 0.13,
#       "hotRate" : -86.44,
#       "avgAmount" : 127.44,
#       "avgAmountRate" : -92.6900,
#       "dealCount" : 8,
#       "dealCountRate" : 13.5600,
#       "publishCount" : 455163,
#       "isFollow" : false,
#       "name" : "三星堆博物馆官方",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/05/04/7-210205105241362_20250504221506A442.jpg"
#     }, {
#       "archiveCount" : 116,
#       "communityIpId" : 37,
#       "marketAmount" : 35971890.00,
#       "marketAmountRate" : 0.6500,
#       "hot" : 1.18,
#       "hotRate" : 53.93,
#       "avgAmount" : 171.19,
#       "avgAmountRate" : -87.0400,
#       "dealCount" : 157,
#       "dealCountRate" : 153.9200,
#       "publishCount" : 337309,
#       "isFollow" : false,
#       "name" : "白月城MoonCity",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/07/24/WechatIMG90_20250724140641A085.jpg"
#     }, {
#       "archiveCount" : 69,
#       "communityIpId" : 89,
#       "marketAmount" : 34342083.90,
#       "marketAmountRate" : 4.0300,
#       "hot" : 14.48,
#       "hotRate" : -44.75,
#       "avgAmount" : 126.85,
#       "avgAmountRate" : -98.7600,
#       "dealCount" : 999,
#       "dealCountRate" : 55.2500,
#       "publishCount" : 254526,
#       "isFollow" : false,
#       "name" : "国宝回家计划",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2026/01/12/fa58fa5ca57a4d53a43933077170fd38_20260112203647A812.jpg"
#     }, {
#       "archiveCount" : 151,
#       "communityIpId" : 38,
#       "marketAmount" : 29553466.74,
#       "marketAmountRate" : -0.1200,
#       "hot" : 0.12,
#       "hotRate" : -70.02,
#       "avgAmount" : 64.62,
#       "avgAmountRate" : -95.9900,
#       "dealCount" : 18,
#       "dealCountRate" : 30.0000,
#       "publishCount" : 444339,
#       "isFollow" : false,
#       "name" : "火种计划",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/16/位图_20250416121506A314.png"
#     }, {
#       "archiveCount" : 80,
#       "communityIpId" : 31,
#       "marketAmount" : 26449717.70,
#       "marketAmountRate" : 0.1200,
#       "hot" : 0.19,
#       "hotRate" : -69.39,
#       "avgAmount" : 74.70,
#       "avgAmountRate" : -93.6800,
#       "dealCount" : 15,
#       "dealCountRate" : 30.6100,
#       "publishCount" : 376678,
#       "isFollow" : false,
#       "name" : "意大利文艺复兴",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415174625A970.png"
#     }, {
#       "archiveCount" : 15,
#       "communityIpId" : 122,
#       "marketAmount" : 25128394.00,
#       "marketAmountRate" : -1.5000,
#       "hot" : 6.27,
#       "hotRate" : -90.16,
#       "avgAmount" : 207.42,
#       "avgAmountRate" : -93.5100,
#       "dealCount" : 94,
#       "dealCountRate" : 9.8400,
#       "publishCount" : 120572,
#       "isFollow" : false,
#       "name" : "中国国家版本馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/09/10/56683610cab445dbb330d474a8e97566_20250910145956A420.jpg"
#     }, {
#       "archiveCount" : 149,
#       "communityIpId" : 145,
#       "marketAmount" : 23452540.29,
#       "marketAmountRate" : -0.3800,
#       "hot" : 0.16,
#       "hotRate" : -77.35,
#       "avgAmount" : 12.12,
#       "avgAmountRate" : -99.4900,
#       "dealCount" : 24,
#       "dealCountRate" : 22.6400,
#       "publishCount" : 649506,
#       "isFollow" : false,
#       "name" : "随州市博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/17/241afbf5c7f24acf8db3409d83c38ad3_20251017135101A535.jpg"
#     }, {
#       "archiveCount" : 98,
#       "communityIpId" : 36,
#       "marketAmount" : 17443710.53,
#       "marketAmountRate" : -0.1200,
#       "hot" : 0.25,
#       "hotRate" : -75.00,
#       "avgAmount" : 57.68,
#       "avgAmountRate" : -86.3800,
#       "dealCount" : 25,
#       "dealCountRate" : 25.0000,
#       "publishCount" : 384895,
#       "isFollow" : false,
#       "name" : "过云楼",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图_20250415181049A098.png"
#     }, {
#       "archiveCount" : 53,
#       "communityIpId" : 21,
#       "marketAmount" : 17161859.81,
#       "marketAmountRate" : 1.0200,
#       "hot" : 1.75,
#       "hotRate" : -92.36,
#       "avgAmount" : 444.88,
#       "avgAmountRate" : -93.9400,
#       "dealCount" : 96,
#       "dealCountRate" : 7.6400,
#       "publishCount" : 245041,
#       "isFollow" : false,
#       "name" : "达文奇的蛋DAVINCIEGG",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/02/20/位图_20250220173924A818.png"
#     }, {
#       "archiveCount" : 94,
#       "communityIpId" : 17,
#       "marketAmount" : 14840684.28,
#       "marketAmountRate" : -0.3800,
#       "hot" : 0.88,
#       "hotRate" : -75.64,
#       "avgAmount" : 30.38,
#       "avgAmountRate" : -98.7500,
#       "dealCount" : 95,
#       "dealCountRate" : 24.3600,
#       "publishCount" : 446219,
#       "isFollow" : false,
#       "name" : "玖央",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/02/12/位图_20250212150945A248.png"
#     }, {
#       "archiveCount" : 65,
#       "communityIpId" : 92,
#       "marketAmount" : 13645604.20,
#       "marketAmountRate" : -0.8600,
#       "hot" : 0.14,
#       "hotRate" : -59.08,
#       "avgAmount" : 20.96,
#       "avgAmountRate" : -96.4700,
#       "dealCount" : 9,
#       "dealCountRate" : 40.9100,
#       "publishCount" : 301364,
#       "isFollow" : false,
#       "name" : "波士顿美术博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/07/30/波士顿_20250730143136A201.png"
#     }, {
#       "archiveCount" : 84,
#       "communityIpId" : 28,
#       "marketAmount" : 13388541.34,
#       "marketAmountRate" : 1.3000,
#       "hot" : 0.35,
#       "hotRate" : -8.33,
#       "avgAmount" : 47.34,
#       "avgAmountRate" : -91.7900,
#       "dealCount" : 33,
#       "dealCountRate" : 91.6700,
#       "publishCount" : 724727,
#       "isFollow" : false,
#       "name" : "北京建院",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/15/位图 2_20250415161501A348.png"
#     }, {
#       "archiveCount" : 72,
#       "communityIpId" : 41,
#       "marketAmount" : 10172211.24,
#       "marketAmountRate" : 0.2100,
#       "hot" : 0.15,
#       "hotRate" : -66.66,
#       "avgAmount" : 101.32,
#       "avgAmountRate" : -45.3000,
#       "dealCount" : 11,
#       "dealCountRate" : 33.3300,
#       "publishCount" : 253417,
#       "isFollow" : false,
#       "name" : "皇家安大略博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/31/adc82841490c4251964c65554d8ba2df_20251031135246A642.jpeg"
#     }, {
#       "archiveCount" : 14,
#       "communityIpId" : 156,
#       "marketAmount" : 9966869.00,
#       "marketAmountRate" : 0.0600,
#       "hot" : 9.07,
#       "hotRate" : -93.36,
#       "avgAmount" : 39.74,
#       "avgAmountRate" : -93.6900,
#       "dealCount" : 127,
#       "dealCountRate" : 6.6400,
#       "publishCount" : 87424,
#       "isFollow" : false,
#       "name" : "西安博物院",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/11/04/31880c9c4067490db4c98fb9bf9d0897_20251104141749A314.jpeg"
#     }, {
#       "archiveCount" : 11,
#       "communityIpId" : 160,
#       "marketAmount" : 9817220.00,
#       "marketAmountRate" : 1.7400,
#       "hot" : 12.73,
#       "hotRate" : -49.82,
#       "avgAmount" : 101.40,
#       "avgAmountRate" : -92.4100,
#       "dealCount" : 140,
#       "dealCountRate" : 50.1800,
#       "publishCount" : 69740,
#       "isFollow" : false,
#       "name" : "数字圆明",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/11/30/6ffa7c9fc07f4afa81a404efa25bf0f1_20251130122249A166.jpg"
#     }, {
#       "archiveCount" : 16,
#       "communityIpId" : 125,
#       "marketAmount" : 9678742.00,
#       "marketAmountRate" : -0.5100,
#       "hot" : 6.18,
#       "hotRate" : -85.15,
#       "avgAmount" : 71.89,
#       "avgAmountRate" : -95.8900,
#       "dealCount" : 105,
#       "dealCountRate" : 14.8500,
#       "publishCount" : 97825,
#       "isFollow" : false,
#       "name" : "浙江省博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/09/16/303f2ce1e99f47628836b1fd8002f3dc_20250916155105A063.jpg"
#     }, {
#       "archiveCount" : 44,
#       "communityIpId" : 78,
#       "marketAmount" : 8383272.79,
#       "marketAmountRate" : 0.0000,
#       "hot" : 0.41,
#       "hotRate" : -93.64,
#       "avgAmount" : 59.27,
#       "avgAmountRate" : -95.5300,
#       "dealCount" : 18,
#       "dealCountRate" : 6.3600,
#       "publishCount" : 246992,
#       "isFollow" : false,
#       "name" : "徐悲鸿纪念馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/07/23/WechatIMG7630_20250723104705A989.jpg"
#     }, {
#       "archiveCount" : 54,
#       "communityIpId" : 13,
#       "marketAmount" : 8257260.49,
#       "marketAmountRate" : -0.2800,
#       "hot" : 0.68,
#       "hotRate" : 35.72,
#       "avgAmount" : 6.27,
#       "avgAmountRate" : -98.5700,
#       "dealCount" : 38,
#       "dealCountRate" : 135.7100,
#       "publishCount" : 278760,
#       "isFollow" : false,
#       "name" : "曲阜三孔",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/02/06/1_20250206101730A721.png"
#     }, {
#       "archiveCount" : 17,
#       "communityIpId" : 132,
#       "marketAmount" : 8233704.40,
#       "marketAmountRate" : 4.3900,
#       "hot" : 5.88,
#       "hotRate" : -8.26,
#       "avgAmount" : 64.37,
#       "avgAmountRate" : -93.9600,
#       "dealCount" : 100,
#       "dealCountRate" : 91.7400,
#       "publishCount" : 101562,
#       "isFollow" : false,
#       "name" : "天津博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/09/4a392df6933c4cb79081209c23f66302_20251009134332A441.png"
#     }, {
#       "archiveCount" : 119,
#       "communityIpId" : 62,
#       "marketAmount" : 7796254.86,
#       "marketAmountRate" : -1.4000,
#       "hot" : 0.33,
#       "hotRate" : -90.40,
#       "avgAmount" : 353.49,
#       "avgAmountRate" : -90.6000,
#       "dealCount" : 39,
#       "dealCountRate" : 9.6100,
#       "publishCount" : 152032,
#       "isFollow" : false,
#       "name" : "苏展设计实验室",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/29/a7146ef5af1f4fe8bd3573fd9c057bb9_20250429160026A342.jpg"
#     }, {
#       "archiveCount" : 25,
#       "communityIpId" : 157,
#       "marketAmount" : 6937680.08,
#       "marketAmountRate" : -0.3200,
#       "hot" : 0.28,
#       "hotRate" : -78.79,
#       "avgAmount" : 82.25,
#       "avgAmountRate" : -90.0200,
#       "dealCount" : 7,
#       "dealCountRate" : 21.2100,
#       "publishCount" : 133234,
#       "isFollow" : false,
#       "name" : "南京市博物总馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/11/07/f108fde7fe2f43938db6369e246a99e6_20251107135612A239.jpg"
#     }, {
#       "archiveCount" : 54,
#       "communityIpId" : 39,
#       "marketAmount" : 6841370.28,
#       "marketAmountRate" : -0.3000,
#       "hot" : 0.61,
#       "hotRate" : 0.00,
#       "avgAmount" : 33.40,
#       "avgAmountRate" : -83.4500,
#       "dealCount" : 34,
#       "dealCountRate" : 100.0000,
#       "publishCount" : 336263,
#       "isFollow" : false,
#       "name" : "大鲸博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/15/大鲸博物馆_20250815221424A986.png"
#     }, {
#       "archiveCount" : 32,
#       "communityIpId" : 80,
#       "marketAmount" : 6761294.63,
#       "marketAmountRate" : -0.4300,
#       "hot" : 1.44,
#       "hotRate" : -39.47,
#       "avgAmount" : 36.24,
#       "avgAmountRate" : -94.0100,
#       "dealCount" : 46,
#       "dealCountRate" : 60.5300,
#       "publishCount" : 141407,
#       "isFollow" : false,
#       "name" : "中国百年巨匠",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/09/01/中国百年巨匠_20250901163608A352.jpg"
#     }, {
#       "archiveCount" : 5,
#       "communityIpId" : 174,
#       "marketAmount" : 6070800.00,
#       "marketAmountRate" : -2.7100,
#       "hot" : 3.40,
#       "hotRate" : -92.89,
#       "avgAmount" : 324.27,
#       "avgAmountRate" : -90.2000,
#       "dealCount" : 17,
#       "dealCountRate" : 7.1100,
#       "publishCount" : 10166,
#       "isFollow" : false,
#       "name" : "秦潮万象",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2026/02/06/85b98b17c5f249848e886aca09c7b0ee_20260206135657A437.jpg"
#     }, {
#       "archiveCount" : 14,
#       "communityIpId" : 114,
#       "marketAmount" : 5772021.00,
#       "marketAmountRate" : 1.7600,
#       "hot" : 0.14,
#       "hotRate" : -87.50,
#       "avgAmount" : 255.50,
#       "avgAmountRate" : -70.8200,
#       "dealCount" : 2,
#       "dealCountRate" : 12.5000,
#       "publishCount" : 81993,
#       "isFollow" : false,
#       "name" : "山西博物院官方",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/18/山西博物馆_20250818152038A020.png"
#     }, {
#       "archiveCount" : 17,
#       "communityIpId" : 14,
#       "marketAmount" : 5473471.76,
#       "marketAmountRate" : 0.0000,
#       "hot" : 0.11,
#       "hotRate" : -95.83,
#       "avgAmount" : 33.50,
#       "avgAmountRate" : -93.2100,
#       "dealCount" : 2,
#       "dealCountRate" : 4.1700,
#       "publishCount" : 82173,
#       "isFollow" : false,
#       "name" : "古中山",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/02/06/IMG_4397_20250206093123A574.PNG"
#     }, {
#       "archiveCount" : 26,
#       "communityIpId" : 85,
#       "marketAmount" : 5401893.00,
#       "marketAmountRate" : 0.3200,
#       "hot" : 0.15,
#       "hotRate" : -88.58,
#       "avgAmount" : 22.00,
#       "avgAmountRate" : -94.8600,
#       "dealCount" : 4,
#       "dealCountRate" : 11.4300,
#       "publishCount" : 139279,
#       "isFollow" : false,
#       "name" : "洛阳博物馆官方",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/07/25/洛阳博物馆官方_20250725151139A048.png"
#     }, {
#       "archiveCount" : 57,
#       "communityIpId" : 10,
#       "marketAmount" : 4141774.00,
#       "marketAmountRate" : 0.1700,
#       "hot" : 0.02,
#       "hotRate" : -83.37,
#       "avgAmount" : 20.00,
#       "avgAmountRate" : -94.1000,
#       "dealCount" : 1,
#       "dealCountRate" : 16.6700,
#       "publishCount" : 83924,
#       "isFollow" : false,
#       "name" : "山海梦",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/01/22/WechatIMG36_20250122144815A177.jpg"
#     }, {
#       "archiveCount" : 6,
#       "communityIpId" : 172,
#       "marketAmount" : 4075300.00,
#       "marketAmountRate" : -0.5400,
#       "hot" : 0.86,
#       "hotRate" : -93.18,
#       "avgAmount" : 5.75,
#       "avgAmountRate" : -98.2400,
#       "dealCount" : 6,
#       "dealCountRate" : 6.8200,
#       "publishCount" : 333230,
#       "isFollow" : false,
#       "name" : "中华文化守护计划",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2026/02/01/da01e2402b6a48afad19ea912d6c89fb_20260201231836A634.png"
#     }, {
#       "archiveCount" : 40,
#       "communityIpId" : 42,
#       "marketAmount" : 3888154.13,
#       "marketAmountRate" : 0.5400,
#       "hot" : 3.57,
#       "hotRate" : -46.62,
#       "avgAmount" : 49.67,
#       "avgAmountRate" : -95.5800,
#       "dealCount" : 150,
#       "dealCountRate" : 53.3800,
#       "publishCount" : 80308,
#       "isFollow" : false,
#       "name" : "聊斋志异",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/04/21/WechatIMG14_20250421144948A351.jpg"
#     }, {
#       "archiveCount" : 37,
#       "communityIpId" : 79,
#       "marketAmount" : 3791750.63,
#       "marketAmountRate" : 0.1900,
#       "hot" : 0.55,
#       "hotRate" : -61.82,
#       "avgAmount" : 53.20,
#       "avgAmountRate" : -82.4300,
#       "dealCount" : 21,
#       "dealCountRate" : 38.1800,
#       "publishCount" : 180265,
#       "isFollow" : false,
#       "name" : "新疆国学书画院",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/07/23/新疆国学书画院_20250723112609A239.jpg"
#     }, {
#       "archiveCount" : 16,
#       "communityIpId" : 144,
#       "marketAmount" : 3739267.00,
#       "marketAmountRate" : -0.1700,
#       "hot" : 1.75,
#       "hotRate" : 21.74,
#       "avgAmount" : 23.99,
#       "avgAmountRate" : -85.7100,
#       "dealCount" : 28,
#       "dealCountRate" : 121.7400,
#       "publishCount" : 77094,
#       "isFollow" : false,
#       "name" : "国艺匠心",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/17/9ad3550f58c74b04a56e6964d85a5fef_20251017095316A029.jpg"
#     }, {
#       "archiveCount" : 45,
#       "communityIpId" : 69,
#       "marketAmount" : 3730584.39,
#       "marketAmountRate" : 2.6800,
#       "hot" : 1.38,
#       "hotRate" : -55.78,
#       "avgAmount" : 117.79,
#       "avgAmountRate" : -88.7100,
#       "dealCount" : 65,
#       "dealCountRate" : 44.2200,
#       "publishCount" : 92247,
#       "isFollow" : false,
#       "name" : "元梦之海",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/05/07/babc7ca94a1049d1b80542d0590ecb61_20250507152838A532.png"
#     }, {
#       "archiveCount" : 11,
#       "communityIpId" : 115,
#       "marketAmount" : 3562719.00,
#       "marketAmountRate" : -1.2700,
#       "hot" : 2.27,
#       "hotRate" : -73.96,
#       "avgAmount" : 67.56,
#       "avgAmountRate" : -90.8300,
#       "dealCount" : 25,
#       "dealCountRate" : 26.0400,
#       "publishCount" : 60974,
#       "isFollow" : false,
#       "name" : "广州艺术博物院",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/18/WechatIMGa8a9222d18bd813460bd0fed64cf4b26_20250818152734A039.jpeg"
#     }, {
#       "archiveCount" : 17,
#       "communityIpId" : 105,
#       "marketAmount" : 3072711.60,
#       "marketAmountRate" : -0.5900,
#       "hot" : 0.82,
#       "hotRate" : -69.57,
#       "avgAmount" : 75.89,
#       "avgAmountRate" : -87.6400,
#       "dealCount" : 14,
#       "dealCountRate" : 30.4300,
#       "publishCount" : 81402,
#       "isFollow" : false,
#       "name" : "中华文化促进会",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/15/中华文化促进会_20250815221532A935.jpg"
#     }, {
#       "archiveCount" : 50,
#       "communityIpId" : 19,
#       "marketAmount" : 2929273.11,
#       "marketAmountRate" : 1.0000,
#       "hot" : 0.20,
#       "hotRate" : -84.06,
#       "avgAmount" : 24.15,
#       "avgAmountRate" : -97.0400,
#       "dealCount" : 11,
#       "dealCountRate" : 15.9400,
#       "publishCount" : 109293,
#       "isFollow" : false,
#       "name" : "暗夜编年史",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/02/13/位图_20250213174015A668.png"
#     }, {
#       "archiveCount" : 31,
#       "communityIpId" : 137,
#       "marketAmount" : 2854497.72,
#       "marketAmountRate" : -0.8700,
#       "hot" : 0.50,
#       "hotRate" : 433.05,
#       "avgAmount" : 27.30,
#       "avgAmountRate" : -94.2500,
#       "dealCount" : 16,
#       "dealCountRate" : 533.3300,
#       "publishCount" : 94905,
#       "isFollow" : false,
#       "name" : "湖南圖書館",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/11/cd0faa6b9a714740ad51af9efacfdfa1_20251011135200A243.png"
#     }, {
#       "archiveCount" : 14,
#       "communityIpId" : 149,
#       "marketAmount" : 2652293.68,
#       "marketAmountRate" : -1.0300,
#       "hot" : 0.00,
#       "hotRate" : -100.00,
#       "avgAmount" : 0.00,
#       "avgAmountRate" : -100.0000,
#       "dealCount" : 0,
#       "dealCountRate" : 0.0000,
#       "publishCount" : 640479,
#       "isFollow" : false,
#       "name" : "宝庆烙画传承人唐文林",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/23/c82e773e4b134aeea3353a8a22b0e4b6_20251023161826A824.jpg"
#     }, {
#       "archiveCount" : 26,
#       "communityIpId" : 153,
#       "marketAmount" : 2587499.07,
#       "marketAmountRate" : 1.7600,
#       "hot" : 1.50,
#       "hotRate" : -51.72,
#       "avgAmount" : 27.70,
#       "avgAmountRate" : -91.9300,
#       "dealCount" : 42,
#       "dealCountRate" : 48.2800,
#       "publishCount" : 98443,
#       "isFollow" : false,
#       "name" : "荣宝斋",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/10/29/9bb74b7a22844b2aa02ef79cf8446fe5_20251029135716A127.jpg"
#     }, {
#       "archiveCount" : 42,
#       "communityIpId" : 103,
#       "marketAmount" : 2577662.86,
#       "marketAmountRate" : -0.4100,
#       "hot" : 0.07,
#       "hotRate" : -57.17,
#       "avgAmount" : 26.66,
#       "avgAmountRate" : -72.4000,
#       "dealCount" : 3,
#       "dealCountRate" : 42.8600,
#       "publishCount" : 68257,
#       "isFollow" : false,
#       "name" : "中华妈祖",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/08/12/上传文件_20250812151634A902.jpeg"
#     }, {
#       "archiveCount" : 24,
#       "communityIpId" : 93,
#       "marketAmount" : 2356712.05,
#       "marketAmountRate" : -0.2000,
#       "hot" : 0.29,
#       "hotRate" : -92.31,
#       "avgAmount" : 27.37,
#       "avgAmountRate" : -93.2800,
#       "dealCount" : 7,
#       "dealCountRate" : 7.6900,
#       "publishCount" : 98796,
#       "isFollow" : false,
#       "name" : "中国对外艺术展",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2025/07/30/对外_20250730143535A314.png"
#     }, {
#       "archiveCount" : 4,
#       "communityIpId" : 171,
#       "marketAmount" : 2327520.00,
#       "marketAmountRate" : -0.3600,
#       "hot" : 14.75,
#       "hotRate" : -76.95,
#       "avgAmount" : 53.42,
#       "avgAmountRate" : -56.9100,
#       "dealCount" : 59,
#       "dealCountRate" : 23.0500,
#       "publishCount" : 36000,
#       "isFollow" : false,
#       "name" : "广州博物馆",
#       "avatar" : "https://cdn2.x-metash.cn/XMeta/2026/01/31/d04cb3d87bee414f999d47eef6d6efd1_20260131202730A383.png"
#     } ],
#     "total" : 75,
#     "size" : 50,
#     "current" : 1,
#     "orders" : [ ],
#     "optimizeCountSql" : true,
#     "hitCount" : false,
#     "countId" : null,
#     "maxLimit" : null,
#     "searchCount" : true,
#     "pages" : 2
#   }
# }
# 

