# 接口名称: 在线藏品 / IP 查询
# 来源文档: spider_process.md
# 说明: 根据关键字搜索在线藏品或 IP。

@baseUrl = https://api.x-metash.cn

### 搜索在线藏品 / IP
POST {{baseUrl}}/h5/home/searchAppNew
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 10,
  "search": "五牛图",
  "isShowArchive": true
}

### 完整响应样本
# 见: 13_home_search_app_new.response.json


### 原始响应样本: 13_home_search_app_new.response.json
# {
#   "code" : 200,
#   "msg" : "成功",
#   "data" : {
#     "archiveList" : [ {
#       "image" : "https://cdn2.x-metash.cn/XMeta/2024/06/20/微信图片_20240620141654_20240620141713A973.jpg",
#       "img" : null,
#       "sellingCount" : 248,
#       "name" : "五牛图",
#       "platformName" : "鲸探",
#       "platformId" : 741,
#       "price" : 540.0,
#       "id" : 29574,
#       "minPriceGoodsId" : 66034519,
#       "type" : 1,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2022/11/02/ui_20221102145345A147.png",
#       "packageCount" : null,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : null,
#       "comingFromThirdParty" : true,
#       "goodsType" : null,
#       "total" : null,
#       "source" : 1,
#       "dealType" : null,
#       "presellDate" : null,
#       "sellStatus" : null,
#       "sellTime" : null,
#       "isArchive" : true,
#       "auctionEndTime" : null,
#       "publishTime" : null,
#       "isPassIn" : null,
#       "maxOfferAmount" : null,
#       "offerUserNum" : null,
#       "collectionNumber" : null,
#       "archiveId" : 29574,
#       "description" : null,
#       "introduce" : null,
#       "goodsMinPriceRate" : -1.82,
#       "isJTTransfer" : true,
#       "isAuthTransfer" : true,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : null,
#       "goodsWantBuyCount" : null,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : null,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : null,
#       "restitutionEndTime" : null,
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : 0,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/02/05/20260205103730A634.jpg",
#       "img" : null,
#       "sellingCount" : 308,
#       "name" : "《五牛图》",
#       "platformName" : "百谷王数字艺术",
#       "platformId" : 29,
#       "price" : 23.5,
#       "id" : 54064,
#       "minPriceGoodsId" : 66020286,
#       "type" : 1,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2025/12/25/84ae0933bd7440bea833c52a3fa5d4b1_20251225144717A873.jpg",
#       "packageCount" : null,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : null,
#       "comingFromThirdParty" : true,
#       "goodsType" : null,
#       "total" : null,
#       "source" : 1,
#       "dealType" : null,
#       "presellDate" : null,
#       "sellStatus" : null,
#       "sellTime" : null,
#       "isArchive" : true,
#       "auctionEndTime" : null,
#       "publishTime" : null,
#       "isPassIn" : null,
#       "maxOfferAmount" : null,
#       "offerUserNum" : null,
#       "collectionNumber" : null,
#       "archiveId" : 54064,
#       "description" : null,
#       "introduce" : null,
#       "goodsMinPriceRate" : -1.59,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : null,
#       "goodsWantBuyCount" : null,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : null,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : null,
#       "restitutionEndTime" : null,
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : 0,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     } ],
#     "archiveTotal" : 4,
#     "ipList" : null,
#     "ipTotal" : null,
#     "goodsNoList" : null,
#     "goodsNoTotal" : null,
#     "goodsList" : [ {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315204250A370.com/chain_myent/afts/img/zR7GSJZMO_0AAAAAAAAAAAAADvN2AQBr/original",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "五牛图#04718/10000",
#       "platformName" : "鲸探",
#       "platformId" : 741,
#       "price" : 550,
#       "id" : 66034521,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2022/11/02/ui_20221102145345A147.png",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 983487,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 20:42:51",
#       "isPassIn" : false,
#       "maxOfferAmount" : 550,
#       "offerUserNum" : 0,
#       "collectionNumber" : "04718/10000",
#       "archiveId" : 29574,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : true,
#       "isAuthTransfer" : true,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315204250A368.com/chain_myent/afts/img/zR7GSJZMO_0AAAAAAAAAAAAADvN2AQBr/original",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "五牛图#04266/10000",
#       "platformName" : "鲸探",
#       "platformId" : 741,
#       "price" : 540,
#       "id" : 66034519,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2022/11/02/ui_20221102145345A147.png",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 983487,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 20:42:50",
#       "isPassIn" : false,
#       "maxOfferAmount" : 540,
#       "offerUserNum" : 0,
#       "collectionNumber" : "04266/10000",
#       "archiveId" : 29574,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : true,
#       "isAuthTransfer" : true,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315204125A109.com/chain_myent/afts/img/zR7GSJZMO_0AAAAAAAAAAAAADvN2AQBr/original",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "五牛图#07548/10000",
#       "platformName" : "鲸探",
#       "platformId" : 741,
#       "price" : 599,
#       "id" : 66034470,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2022/11/02/ui_20221102145345A147.png",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 993286,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 20:41:25",
#       "isPassIn" : false,
#       "maxOfferAmount" : 599,
#       "offerUserNum" : 0,
#       "collectionNumber" : "07548/10000",
#       "archiveId" : 29574,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : true,
#       "isAuthTransfer" : true,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "https://cdn2.x-metash.cn/XMeta/2024/06/20/微信图片_20240620141654_20240620141713A973.jpg",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "五牛图",
#       "platformName" : "鲸探",
#       "platformId" : 741,
#       "price" : 530,
#       "id" : 66032609,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2022/11/02/ui_20221102145345A147.png",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 12961,
#       "comingFromThirdParty" : false,
#       "goodsType" : 4,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 20:04:30",
#       "isPassIn" : false,
#       "maxOfferAmount" : 530,
#       "offerUserNum" : 0,
#       "collectionNumber" : "",
#       "archiveId" : 29574,
#       "description" : "请自行填写编号",
#       "introduce" : "请自行填写编号",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 0,
#       "goodsWantBuyCount" : 1,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315163604A907.jpg",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "《五牛图》#2792/4000",
#       "platformName" : "百谷王数字艺术",
#       "platformId" : 29,
#       "price" : 23.5,
#       "id" : 66020291,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2025/12/25/84ae0933bd7440bea833c52a3fa5d4b1_20251225144717A873.jpg",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 1081980,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 16:36:05",
#       "isPassIn" : false,
#       "maxOfferAmount" : 23.5,
#       "offerUserNum" : 0,
#       "collectionNumber" : "2792/4000",
#       "archiveId" : 54064,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315163604A906.jpg",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "《五牛图》#2784/4000",
#       "platformName" : "百谷王数字艺术",
#       "platformId" : 29,
#       "price" : 23.5,
#       "id" : 66020290,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2025/12/25/84ae0933bd7440bea833c52a3fa5d4b1_20251225144717A873.jpg",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 1081980,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 16:36:05",
#       "isPassIn" : false,
#       "maxOfferAmount" : 23.5,
#       "offerUserNum" : 0,
#       "collectionNumber" : "2784/4000",
#       "archiveId" : 54064,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315163602A903.jpg",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "《五牛图》#3954/4000",
#       "platformName" : "百谷王数字艺术",
#       "platformId" : 29,
#       "price" : 23.5,
#       "id" : 66020287,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2025/12/25/84ae0933bd7440bea833c52a3fa5d4b1_20251225144717A873.jpg",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 1081980,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 16:36:03",
#       "isPassIn" : false,
#       "maxOfferAmount" : 23.5,
#       "offerUserNum" : 0,
#       "collectionNumber" : "3954/4000",
#       "archiveId" : 54064,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315163602A901.jpg",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "《五牛图》#2773/4000",
#       "platformName" : "百谷王数字艺术",
#       "platformId" : 29,
#       "price" : 23.5,
#       "id" : 66020285,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2025/12/25/84ae0933bd7440bea833c52a3fa5d4b1_20251225144717A873.jpg",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 1081980,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 16:36:02",
#       "isPassIn" : false,
#       "maxOfferAmount" : 23.5,
#       "offerUserNum" : 0,
#       "collectionNumber" : "2773/4000",
#       "archiveId" : 54064,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/15/20260315133610A887.jpg",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "《五牛图》#2462/4000",
#       "platformName" : "百谷王数字艺术",
#       "platformId" : 29,
#       "price" : 23.99,
#       "id" : 66009750,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2025/12/25/84ae0933bd7440bea833c52a3fa5d4b1_20251225144717A873.jpg",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 40249,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-15 13:36:11",
#       "isPassIn" : false,
#       "maxOfferAmount" : 23.99,
#       "offerUserNum" : 0,
#       "collectionNumber" : "2462/4000",
#       "archiveId" : 54064,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : false,
#       "isAuthTransfer" : false,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     }, {
#       "image" : "http://xmeta4.oss-accelerate.aliyuncs.com/XMeta_goods/2026/03/14/20260314232021A049.com/chain_myent/afts/img/zR7GSJZMO_0AAAAAAAAAAAAADvN2AQBr/original",
#       "img" : null,
#       "sellingCount" : 1,
#       "name" : "五牛图#01096/10000",
#       "platformName" : "鲸探",
#       "platformId" : 741,
#       "price" : 999,
#       "id" : 65970427,
#       "minPriceGoodsId" : null,
#       "type" : 2,
#       "platformIcon" : "https://cdn2.x-metash.cn/XMeta/2022/11/02/ui_20221102145345A147.png",
#       "packageCount" : 1,
#       "isCrown" : false,
#       "illegalCount" : 0,
#       "uid" : 6530,
#       "comingFromThirdParty" : true,
#       "goodsType" : 1,
#       "total" : 17101,
#       "source" : null,
#       "dealType" : 0,
#       "presellDate" : "1970-01-01 08:00:00",
#       "sellStatus" : 1,
#       "sellTime" : "1970-01-01 08:00:00",
#       "isArchive" : null,
#       "auctionEndTime" : "1970-01-01 08:00:00",
#       "publishTime" : "2026-03-14 23:20:22",
#       "isPassIn" : false,
#       "maxOfferAmount" : 999,
#       "offerUserNum" : 0,
#       "collectionNumber" : "01096/10000",
#       "archiveId" : 29574,
#       "description" : "",
#       "introduce" : "",
#       "goodsMinPriceRate" : null,
#       "isJTTransfer" : true,
#       "isAuthTransfer" : true,
#       "wantBuyMaxPrice" : null,
#       "maxWantBuyPriceGoodsId" : null,
#       "wantBuyCount" : null,
#       "count" : 1,
#       "goodsWantBuyCount" : 0,
#       "wantBuyMaxPriceTime" : null,
#       "isPayBond" : false,
#       "rentHireMaxPrice" : null,
#       "rentHireMaxUnitPrice" : null,
#       "maxRentHirePriceGoodsId" : null,
#       "rentHireCount" : null,
#       "rentHireMaxPriceTime" : null,
#       "rentRequestEndTime" : "1970-01-01 08:00:00",
#       "restitutionEndTime" : "1970-01-01 08:00:00",
#       "marketAmount" : null,
#       "marketAmountRate" : null,
#       "dealCount" : null,
#       "dealCountRate" : null,
#       "nftHoldCount" : null,
#       "nftSellingCount" : null,
#       "seriesTitle" : null,
#       "isFollow" : null,
#       "holdNftArchive" : null,
#       "minPriceTime" : null
#     } ],
#     "goodsTotal" : 17101
#   }
# }
# 

